### ISSUE TITLE
Source Code has moved to GitHub

### ISSUE THREAD

**Issue by jcoutch** [dmanning23/SteelBattalion.NET#1]
Hey, I'm the original developer of the Steel Battalion source code.  Just letting you know that with the announcement about CodePlex closing down, I migrated it to GitHub:

https://github.com/jcoutch/steel-battalion-net

I'm hoping to give the project a little love sometime soon.  Just thought I'd drop you a note in case you want to fork from my repo/merge pull requests later on.  :-)

**Comment by dmanning23** [comment]
Awesome, thanks for the heads up! Yeah if you are continuing work on this project I will probably delete this repo and fork yours in the future.

Cheers!
